### ISSUE TITLE
MacOS 11.6 Big Sur: unable to compile PHP

### ISSUE THREAD

**Issue by jrmgx** [phpbrew/phpbrew#1249]
Hello,

First of all thank you for this tool,
I'd love to use it but I have some trouble installing a PHP version, maybe you could help?

### Output

```
/Users/jrmgx/.phpbrew/build/php-8.0.10/ext/openssl/openssl.c:1224:51: 
error: use of undeclared identifier 'RSA_SSLV23_PADDING'
```

### Expected Result

PHP compiled and working

### Command

`phpbrew --debug install 8.0 +default`
Similar error with 7.4

### Build Log

Full log https://pastebin.com/krPZaimq
The important part would be
```
/bin/sh /Users/jerome/.phpbrew/build/php-8.0.10/libtool --silent --preserve-dup-deps --mode=compile cc -Iext/openssl/ \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/ext/openssl/ \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/include \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/main \
    -I/Users/jerome/.phpbrew/build/php-8.0.10 \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/ext/date/lib \
    -I/usr/local/Cellar/libxml2/2.9.12/include/libxml2 \
    -I/usr/local/Cellar/openssl@3/3.0.0/include \
    -I/usr/local/opt/bzip2/include \
    -I/usr/local/Cellar/curl/7.79.1/include \
    -I/usr/local/Cellar/oniguruma/6.9.7.1/include \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/ext/mbstring/libmbfl \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/ext/mbstring/libmbfl/mbfl \
    -I/usr/local/opt/readline/include \
    -I/usr/local/Cellar/libzip/1.8.0/include \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/TSRM \
    -I/Users/jerome/.phpbrew/build/php-8.0.10/Zend  \
    -no-cpp-precomp  -Wall -Wextra -Wno-strict-aliasing \
    -Wno-implicit-fallthrough -Wno-unused-parameter -Wno-sign-compare \
    -g -O2 -fvisibility=hidden -DZEND_SIGNALS    \
    -c /Users/jerome/.phpbrew/build/php-8.0.10/ext/openssl/openssl.c -o ext/openssl/openssl.lo 
/Users/jerome/.phpbrew/build/php-8.0.10/ext/openssl/openssl.c:1224:51: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
        REGISTER_LONG_CONSTANT("OPENSSL_SSLV23_PADDING", RSA_SSLV23_PADDING, CONST_CS|CONST_PERSISTENT);
                                                         ^
```

### Platform

MacOs 11.6 Big Sur

```
$ phpbrew --version
phpbrew - 1.27.0
cliframework core: 2.5.4

$ brew --version
Homebrew 3.2.13

$ brew list
==> Formulae
autoconf	curl		libev		libunistring	m4		mutagen		openldap	popt		rtmpdump	xxhash
brotli		gdbm		libiconv	libxml2		mhash		mutagen-beta	openssl@1.1	python@3.9	sqlite		xz
bzip2		gettext		libidn2		libzip		mkcert		nghttp2		openssl@3	readline	unison		zlib
c-ares		jemalloc	libssh2		lz4		mpdecimal	oniguruma	pkg-config	rsync		unox		zstd
```

**Comment by jrmgx** [comment]
After some long investigation,
it worked by removing openssl@3 from my system (`brew uninstall openssl@3`) 
and using this command line to compile
`OPENSSL_CFLAGS="-I/usr/local/opt/openssl@1.1/include" OPENSSL_LIBS="-L/usr/local/opt/openssl@1.1/lib -lcrypto -lssl" phpbrew install 8.0 +default`

I let this ticket open as it would be lovely that phpbrew detect everything automatically :)

**Comment by TheNorthMemory** [comment]
It works on `macOS 10.13.6 High Sierra` without `openssl@3` installation:

```
brew --version
Homebrew 3.2.16
```

```
phpbrew --version
phpbrew - 1.27.0
cliframework core: 2.5.4
```

```
PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/pkgconfig:$PKG_CONFIG_PATH" \
OPENSSL_PREFIX=$(brew --prefix openssl@1.1) \
PATH="/usr/local/opt/bison/bin:$PATH" \
phpbrew install --no-config-cache 8.1.0RC4 +default +openssl=/usr/local/opt/openssl@1.1
```

**Comment by junseinagao** [comment]
This issue helped to solve my problem. Thanks to @jrmgx.

**Comment by peckrob** [comment]
I ran into this problem @vpArth hit, as well as the one in #1251. I was able to successfully get php to build using the following command:

```shell
$ OPENSSL_CFLAGS="-I`brew --prefix openssl@1.1`/include" \
OPENSSL_LIBS="-L`brew --prefix openssl@1.1`/lib -lcrypto -lssl" \
phpbrew --debug install --stdout -j `nproc` 7.4 +dev -- --with-pcre-regex=`brew --prefix pcre2` --without-pcre-jit
```

For ease, I added it to the config.yaml file:

```yaml
variants:
  dev:
    ...
    pcre:
      "--with-pcre-regex": "`brew --prefix pcre2`"
      "--without-pcre-jit":
```

**Comment by vpArth** [comment]
```
Congratulations! Now you have PHP with 7.3.31 as php-7.3.31
```
Thank you, @peckrob!

**Comment by filiplikavcan** [comment]
When I run:

```
OPENSSL_CFLAGS="-I/usr/local/opt/openssl@1.1/include" \
OPENSSL_LIBS="-L/usr/local/opt/openssl@1.1/lib -lcrypto -lssl" \
phpbrew install -j 16 8.0 +default
```

I get (on Monterey) this error: 

```
Undefined symbols for architecture x86_64:
  "_EVP_CIPHER_CTX_block_size", referenced from:
      _zif_openssl_seal in openssl.o
  "_EVP_CIPHER_block_size", referenced from:
      _php_openssl_cipher_update in openssl.o
  "_EVP_CIPHER_flags", referenced from:
      _php_openssl_encrypt in openssl.o
      _php_openssl_decrypt in openssl.o
  "_EVP_CIPHER_iv_length", referenced from:
      _zif_openssl_seal in openssl.o
      _zif_openssl_open in openssl.o
      _php_openssl_cipher_init in openssl.o
      _php_openssl_cipher_iv_length in openssl.o
      _zif_openssl_cipher_iv_length in openssl.o
  "_EVP_CIPHER_key_length", referenced from:
      _php_openssl_cipher_init in openssl.o
  "_EVP_MD_size", referenced from:
      _zif_openssl_digest in openssl.o
  "_EVP_PKEY_base_id", referenced from:
      _zif_openssl_pkey_export_to_file in openssl.o
      _zif_openssl_pkey_export in openssl.o
      _zif_openssl_pkey_get_details in openssl.o
      _zif_openssl_dh_compute_key in openssl.o
  "_EVP_PKEY_bits", referenced from:
      _zif_openssl_pkey_get_details in openssl.o
  "_EVP_PKEY_id", referenced from:
      _php_openssl_pkey_from_zval in openssl.o
      _zif_openssl_private_encrypt in openssl.o
      _zif_openssl_private_decrypt in openssl.o
      _zif_openssl_public_encrypt in openssl.o
      _zif_openssl_public_decrypt in openssl.o
  "_EVP_PKEY_size", referenced from:
      _zif_openssl_private_encrypt in openssl.o
      _zif_openssl_private_decrypt in openssl.o
      _zif_openssl_public_encrypt in openssl.o
      _zif_openssl_public_decrypt in openssl.o
      _zif_openssl_sign in openssl.o
      _zif_openssl_seal in openssl.o
      _phar_create_signature in util.o
      ...
  "_SSL_get_peer_certificate", referenced from:
      _php_openssl_sockop_set_option in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/phpdbg/phpdbg] Error 1
```

**Comment by filiplikavcan** [comment]
This works:

```
export OPENSSL_PREFIX=$(brew --prefix openssl@1.1)
export OPENSSL_CFLAGS="-I${OPENSSL_PREFIX}/include"
export OPENSSL_LIBS="-L${OPENSSL_PREFIX}/lib -lcrypto -lssl"

phpbrew --debug install -j 16 8.0 +default -- --with-openssl="shared,${OPENSSL_PREFIX}"
phpbrew ext install openssl
```

**Comment by usacom** [comment]
It is still not working for me.

![telegram-cloud-photo-size-2-5447206266335247376-y](https://user-images.githubusercontent.com/6668629/151447495-322946c9-fac8-4441-8d7a-833a7b8e864f.jpg)

![image](https://user-images.githubusercontent.com/6668629/151447572-d3c3e114-4a53-4ff7-bf16-328c5777e5c3.png)

mac OS Monterey (intel based)

**Comment by zang3tsu** [comment]
Just to re-iterate what @filiplikavcan did, this is all the commands that I used to install PHP 7.4 on Monterey:

1. Install PHP 8.0 first using phpbrew
```
export OPENSSL_PREFIX=$(brew --prefix openssl@1.1)
export OPENSSL_CFLAGS="-I${OPENSSL_PREFIX}/include"
export OPENSSL_LIBS="-L${OPENSSL_PREFIX}/lib -lcrypto -lssl"

phpbrew --debug install -j 12 8.0 +default -- --with-openssl="shared,${OPENSSL_PREFIX}"
```
2. Switch to it
```
phpbrew use php-8.0.20
```
3. Install openssl extension
```
phpbrew ext install openssl -- --with-openssl=$OPENSSL_PREFIX
```
4. Now install PHP 7.4 (in the same terminal)
```
export CFLAGS="-Wno-implicit-function-declaration"

phpbrew install -j 12 7.4 +default -- --with-openssl="shared,${OPENSSL_PREFIX}"
```

**Comment by mackensen** [comment]
> Just to re-iterate what @filiplikavcan did, this is all the commands that I used to install PHP 7.4 on Monterey:
> 
> 1. Install PHP 8.0 first using phpbrew
> 
> ```
> export OPENSSL_PREFIX=$(brew --prefix openssl@1.1)
> export OPENSSL_CFLAGS="-I${OPENSSL_PREFIX}/include"
> export OPENSSL_LIBS="-L${OPENSSL_PREFIX}/lib -lcrypto -lssl"
> 
> phpbrew --debug install -j 12 8.0 +default -- --with-openssl="shared,${OPENSSL_PREFIX}"
> ```
> 
> 2. Switch to it
> 
> ```
> phpbrew use php-8.0.20
> ```
> 
> 3. Install openssl extension
> 
> ```
> phpbrew ext install openssl -- --with-openssl=$OPENSSL_PREFIX
> ```
> 
> 4. Now install PHP 7.4 (in the same terminal)
> 
> ```
> export CFLAGS="-Wno-implicit-function-declaration"
> 
> phpbrew install -j 12 7.4 +default -- --with-openssl="shared,${OPENSSL_PREFIX}"
> ```

This worked for me, but to actually enable openssl for PHP 7.4 I did this after switching to PHP 7.4:

```
export OPENSSL_PREFIX=$(brew --prefix openssl@1.1)
phpbrew ext install openssl -- --with-openssl=$OPENSSL_PREFIX
```

**Comment by IvorNetJam** [comment]
When following this, I get:
thrown in /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php on line 1133

make: *** [ext/phar/phar.phar] Error 255

Please checkout the build log file for more details:

Fatal error: Uncaught InvalidArgumentException: RegexIterator::__construct(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php:1133
Stack trace:
#0 /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php(1133): RegexIterator->__construct(Object(RecursiveIteratorIterator), '/\\.svn/')
#1 /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php(1077): PharCommand::phar_add(Object(Phar), 0, '/Users/ivor/.ph...', NULL, '/\\.svn/', Object(SplFileInfo), NULL, true)
#2 /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php(225): PharCommand->cli_cmd_run_pack(Array)
#3 /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php(2089): CLICommand->__construct(19, Array)
#4 {main}
  thrown in /Users/ivor/.phpbrew/build/php-8.0.22/ext/phar/phar.php on line 1133
make: *** [ext/phar/phar.phar] Error 255


When editing the file it doesn't make a difference (seems to be overwritten)

**Comment by theofidry** [comment]
Not 100% if it's the right solution, but I remember having to do `-- --without-pcre-jit`
