### ISSUE TITLE
Can't compile on Ubuntu 13.10 due to libxml2

### ISSUE THREAD

**Issue by malte-witt** [phpbrew/phpbrew#152]
When trying to compile any PHP version I get the following error:

/home/.phpbrew/build/php-5.4.0/ext/dom/node.c: In function ‘dom_canonicalization’:
/home/.phpbrew/build/php-5.4.0/ext/dom/node.c:1898:21: error: dereferencing pointer to incomplete type

I was able to fix this error by using the patch attached to this message https://mail.gnome.org/archives/xml/2012-August/msg00028.html

i.e. doing:
wget https://mail.gnome.org/archives/xml/2012-August/txtbgxGXAvz4N.txt
patch -p0 -b txtbgxGXAvz4N.txt

and then performing the configure command like it is outputted by the debug switch. The compile process will run fine after applying the patch, but of course unfortunately I still won't have an PHP version installed in phpbrew after this.

Is there any workaround to have phpbrew use a custom patch before compiling?

**Comment by Rahal07** [comment]
Hi,
i tried to run the command: patch -p0 -b txtbgxGXAvz4N.txt inside of php install folder, but nothing happens.
![screenshot from 2015-06-05 12 18 00](https://cloud.githubusercontent.com/assets/12761583/8005004/0578a4be-0b7d-11e5-9b06-ecd208380615.png)

**Comment by marcioAlmada** [comment]
It's supposed to be:

    phpbrew install --patch [File Path] <php-version>

**Comment by Rahal07** [comment]
no, i'm trying to install php 5.3.3 using a its source, but i got an error while compiling 
/php-5.3.3/ext/dom/node.c: In function ‘dom_canonicalization’:
/php-5.3.3/ext/dom/node.c:1903:21: error: dereferencing pointer to incomplete type
so this is why i tried to run this patch in order to solve this problem...

**Comment by tassoevan** [comment]
I've a problem similar to this reported by @Rahal07.

```
/home/tasso/.phpbrew/build/php-5.3.3/ext/dom/node.c: In function ‘dom_canonicalization’:
/home/tasso/.phpbrew/build/php-5.3.3/ext/dom/node.c:1903:21: error: dereferencing pointer to incomplete type
    ret = buf->buffer->use;
                     ^
In file included from /home/tasso/.phpbrew/build/php-5.3.3/main/php.h:38:0,
                 from /home/tasso/.phpbrew/build/php-5.3.3/ext/dom/node.c:26:
/home/tasso/.phpbrew/build/php-5.3.3/ext/dom/node.c:1905:40: error: dereferencing pointer to incomplete type
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
                                        ^
/home/tasso/.phpbrew/build/php-5.3.3/Zend/zend_API.h:545:20: note: in definition of macro ‘ZVAL_STRINGL’
   const char *__s=(s); int __l=l;  \
                    ^
/home/tasso/.phpbrew/build/php-5.3.3/ext/dom/node.c:1905:5: note: in expansion of macro ‘RETVAL_STRINGL’
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
     ^
make: ** [ext/dom/node.lo] Erro 1
```

**Comment by marcioAlmada** [comment]
> no, i'm trying to install php 5.3.3 using a its source, but i got an error while compiling

You should apply the patch using the `--patch` option, avoid doing it by yourself. Sometimes phpbrew will extract the source again and undo whatever you did in the src folder.

**Comment by tapankumar** [comment]
I had faced the same issue while compiling php 5.3.3 on centos 7 64 bit so below are the commands through which i have resolved my issue.

Go to the root directory of PHP 5.3.3 source code
patch -p0 < txtbgxGXAvz4N.txt

Then i got stuck into below error.
/bin/ld: note: '__gxx_personality_v0@@CXXABI_1.3' is defined in DSO /lib64/libstdc++.so.6 so try adding it to the linker command line
/lib64/libstdc++.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1

Then this command helped me.
Go to the root directory of PHP 5.3.3 source code
sed -i '/^BUILD_/ s/\$(CC)/\$(CXX)/g' Makefile

Source: http://www.gcos.me/2012-10-19_how-to-compile-php53-on-64bit-linux-macos.html
