### ISSUE TITLE
Cannot compile with apxs2 on ubuntu 14.04

### ISSUE THREAD

**Issue by arbet** [phpbrew/phpbrew#302]
I'm trying to compile PHP 5.4.31 using the following command

`phpbrew install 5.4.31 +default +gd +json +apxs2=/usr/bin/apxs2`

It works without "+apxs2=/usr/bin/apxs2" , but when I add apxs2, I receive the following error

`/home/samer/.phpbrew/build/php-5.4.31/ext/standard/browscap.c:401: undefined reference to 'php_pcre_exec'
ext/pcre/php_pcre.o: In function 'zm_info_pcre':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:128: undefined reference to 'php_pcre_version'
ext/pcre/php_pcre.o: In function 'zm_startup_pcre':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:154: undefined reference to 'php_pcre_version'
ext/pcre/php_pcre.o: In function 'make_subpats_table':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:193: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:202: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:203: undefined reference to 'php_pcre_fullinfo'
ext/pcre/php_pcre.o: In function 'pcre_get_compiled_regex_cache':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:267: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:399: undefined reference to 'php_pcre_compile'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:395: undefined reference to 'php_pcre_maketables'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:417: undefined reference to 'php_pcre_study'
ext/pcre/php_pcre.o: In function 'php_pcre_match_impl':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:624: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:659: undefined reference to 'php_pcre_exec'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:678: undefined reference to 'php_pcre_get_substring_list'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:749: undefined reference to 'php_pcre_free'
ext/pcre/php_pcre.o: In function 'php_pcre_replace_impl':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1056: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1087: undefined reference to 'php_pcre_exec'
ext/pcre/php_pcre.o: In function 'php_pcre_split_impl':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1520: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1536: undefined reference to 'php_pcre_exec'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1600: undefined reference to 'php_pcre_exec'
ext/pcre/php_pcre.o: In function 'php_pcre_grep_impl':
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1784: undefined reference to 'php_pcre_fullinfo'
/home/samer/.phpbrew/build/php-5.4.31/ext/pcre/php_pcre.c:1808: undefined reference to 'php_pcre_exec'
ext/fileinfo/libmagic/softmagic.o: In function 'check_fmt':
/home/samer/.phpbrew/build/php-5.4.31/ext/fileinfo/libmagic/softmagic.c:357: undefined reference to 'php_pcre_exec'
ext/filter/logical_filters.o: In function 'php_filter_validate_regexp':
/home/samer/.phpbrew/build/php-5.4.31/ext/filter/logical_filters.c:439: undefined reference to 'php_pcre_exec'
ext/filter/logical_filters.o: In function 'php_filter_validate_email':
/home/samer/.phpbrew/build/php-5.4.31/ext/filter/logical_filters.c:547: undefined reference to 'php_pcre_exec'
ext/readline/readline.o: In function 'zif_readline_info':
/home/samer/.phpbrew/build/php-5.4.31/ext/readline/readline.c:278: undefined reference to 'rl_mark'
/home/samer/.phpbrew/build/php-5.4.31/ext/readline/readline.c:251: undefined reference to 'rl_mark'
/home/samer/.phpbrew/build/php-5.4.31/ext/readline/readline.c:253: undefined reference to 'rl_pending_input'
/home/samer/.phpbrew/build/php-5.4.31/ext/readline/readline.c:287: undefined reference to 'rl_pending_input'
/home/samer/.phpbrew/build/php-5.4.31/ext/readline/readline.c:290: undefined reference to 'rl_pending_input'
ext/readline/readline.o: In function 'zif_readline_list_history':
/home/samer/.phpbrew/build/php-5.4.31/ext/readline/readline.c:371: undefined reference to 'history_list'
ext/spl/spl_iterators.o: In function 'zim_spl_RegexIterator_accept':
/home/samer/.phpbrew/build/php-5.4.31/ext/spl/spl_iterators.c:2022: undefined reference to 'php_pcre_exec'
ext/zip/php_zip.o: In function 'php_zip_pcre':
/home/samer/.phpbrew/build/php-5.4.31/ext/zip/php_zip.c:708: undefined reference to 'php_pcre_exec'
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1
`

Any idea what might be causing this?
